// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateMerchantRequest defines model for CreateMerchantRequest.
type CreateMerchantRequest struct {
	Name string `json:"name"`
}

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	Amount     string `json:"amount"`
	MerchantId int    `json:"merchant_id"`
	Status     string `json:"status"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Merchant defines model for Merchant.
type Merchant struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount       *string    `json:"amount,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Id           *string    `json:"id,omitempty"`
	MerchantId   *int       `json:"merchant_id,omitempty"`
	MerchantName *string    `json:"merchant_name,omitempty"`
	Status       *string    `json:"status,omitempty"`
}

// ReviewPaymentRequest defines model for ReviewPaymentRequest.
type ReviewPaymentRequest struct {
	Status string `json:"status"`
}

// UpdateMerchantRequest defines model for UpdateMerchantRequest.
type UpdateMerchantRequest struct {
	Name string `json:"name"`
}

// UpdatePaymentRequest defines model for UpdatePaymentRequest.
type UpdatePaymentRequest struct {
	Amount     string `json:"amount"`
	MerchantId int    `json:"merchant_id"`
	Status     string `json:"status"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// Search defines model for search.
type Search = string

// Sort defines model for sort.
type Sort = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// MerchantListResponse defines model for MerchantListResponse.
type MerchantListResponse struct {
	Limit      int        `json:"limit"`
	Merchants  []Merchant `json:"merchants"`
	Page       int        `json:"page"`
	Total      int        `json:"total"`
	TotalPages int        `json:"total_pages"`
}

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments *[]Payment `json:"payments,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1MerchantsParams defines parameters for GetDashboardV1Merchants.
type GetDashboardV1MerchantsParams struct {
	// Search Free-text search term for list filtering
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Page Page number (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Search Free-text search term for list filtering
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Status status of payment (completed, processing, or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// PostDashboardV1MerchantsJSONRequestBody defines body for PostDashboardV1Merchants for application/json ContentType.
type PostDashboardV1MerchantsJSONRequestBody = CreateMerchantRequest

// PutDashboardV1MerchantsIdJSONRequestBody defines body for PutDashboardV1MerchantsId for application/json ContentType.
type PutDashboardV1MerchantsIdJSONRequestBody = UpdateMerchantRequest

// PostDashboardV1PaymentsJSONRequestBody defines body for PostDashboardV1Payments for application/json ContentType.
type PostDashboardV1PaymentsJSONRequestBody = CreatePaymentRequest

// PutDashboardV1PaymentsIdJSONRequestBody defines body for PutDashboardV1PaymentsId for application/json ContentType.
type PutDashboardV1PaymentsIdJSONRequestBody = UpdatePaymentRequest

// PutDashboardV1PaymentsIdReviewJSONRequestBody defines body for PutDashboardV1PaymentsIdReview for application/json ContentType.
type PutDashboardV1PaymentsIdReviewJSONRequestBody = ReviewPaymentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List merchants
	// (GET /dashboard/v1/merchants)
	GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request, params GetDashboardV1MerchantsParams)
	// Create a merchant
	// (POST /dashboard/v1/merchants)
	PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request)
	// Delete a merchant
	// (DELETE /dashboard/v1/merchants/{id})
	DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// Get a merchant
	// (GET /dashboard/v1/merchants/{id})
	GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// Update a merchant
	// (PUT /dashboard/v1/merchants/{id})
	PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// List payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
	// Create a payment
	// (POST /dashboard/v1/payments)
	PostDashboardV1Payments(w http.ResponseWriter, r *http.Request)
	// Delete a payment
	// (DELETE /dashboard/v1/payments/{id})
	DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string)
	// Update a payment
	// (PUT /dashboard/v1/payments/{id})
	PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string)
	// Review payment (update status)
	// (PUT /dashboard/v1/payments/{id}/review)
	PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List merchants
// (GET /dashboard/v1/merchants)
func (_ Unimplemented) GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request, params GetDashboardV1MerchantsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a merchant
// (POST /dashboard/v1/merchants)
func (_ Unimplemented) PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a merchant
// (DELETE /dashboard/v1/merchants/{id})
func (_ Unimplemented) DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a merchant
// (GET /dashboard/v1/merchants/{id})
func (_ Unimplemented) GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a merchant
// (PUT /dashboard/v1/merchants/{id})
func (_ Unimplemented) PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a payment
// (POST /dashboard/v1/payments)
func (_ Unimplemented) PostDashboardV1Payments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a payment
// (DELETE /dashboard/v1/payments/{id})
func (_ Unimplemented) DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a payment
// (PUT /dashboard/v1/payments/{id})
func (_ Unimplemented) PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Review payment (update status)
// (PUT /dashboard/v1/payments/{id}/review)
func (_ Unimplemented) PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Merchants operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1MerchantsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Merchants(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1Merchants operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1Merchants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1Payments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDashboardV1PaymentsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDashboardV1PaymentsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentsId operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentsIdReview operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentsIdReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/merchants", wrapper.GetDashboardV1Merchants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/merchants", wrapper.PostDashboardV1Merchants)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.DeleteDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.GetDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.PutDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/payments", wrapper.PostDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dashboard/v1/payments/{id}", wrapper.DeleteDashboardV1PaymentsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payments/{id}", wrapper.PutDashboardV1PaymentsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payments/{id}/review", wrapper.PutDashboardV1PaymentsIdReview)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZW3PbNhP9Kxh834M9pU2qcWYynOlDLk3Gnbj1JHX7kGpimFxJSEgAAUDHqkb/vQOA",
	"VxGU6Jtav1kmuHt29+ziAFzhhOeCM2Ba4XiFBZEkBw3S/spoTrX5IwWVSCo05QzH+NcivwKJ+AxRDblC",
	"AiQSZA7oICc3aBJFhzjA1Kz8VoBc4gAzkgOOS3sBVskCcuIMz0iRaRxPogDn5IbmRW5+mF+Ulb8CrJfC",
	"vE+ZhjlIvF4H2DjsQzs3MJjDdzA5uiIK0iE01oIfzE7vCohMFn3/byXAkYYbjdwKpEHmaMYlyqjSaEYz",
	"DZKy+QCk0mwbFNyQXGTmoeZfOa7RKG3tWDBceqr0muc5OVJgSqohRWYVmlHIUnWMzEPOkCBag2QqRpdH",
	"iQSz7jPRl+hASJjRG3R5dIl+QsbuIbokOS+Yecg46jwnKjn8iw2FZMD5A2q59MS1DrAEJThTYMn4iqQf",
	"4FsBSv8sJZfmXwlnGpiNnQiR0YSY2MMvyiRg1fL5fwkzHOP/hQ3bQ/dUhc6a9ddNYOkNXZOMptYymhGa",
	"QYrXAT5lJnEk+wjyGuSeEFVOkbJeEbiFAX7P55R9KLP1YDguFHhhSNCFZEjzr8AQYSkqFEhE2YzL3Pox",
	"kM5AJgvC9Huq9J2QkSz7bYbjT9sxnpM5ZdbEGWiC18EKC8kFSE0dbfISh/1h59WusCvkJoqSlERKssSO",
	"kt8KKiHF8aeW6Wm9kl99gUTj9dSTt8owMjkx1s/JMod7pKgbqXDWxgdauvfGuRFOP5jy5TqWC0YKveCS",
	"/g3p2HYoR4EFWtj3gWmzyOR3hVWR50QuTeaoUpTNETc0s/3o2IcDfE2yosxaCjg+iczwBqXs9oDz8kVj",
	"Gy2ApBWj79mJLxuszVww8CqHiYTULCCZwo0/G+lrO/UqMpRTpl9ONz9Xnnnf5qBd1adfUHopqzToxM10",
	"j5ugZvdnmrae15tggJUmulC7IbYNBZXH+nUf9po/XbCuwq0dxBa7D6wuf3uzuejyK64r5eHU9ngsjMaL",
	"L4B6hPRjaLa8eIXdxMQxTomGI01z6HsP8FABBhgS4EKkt3Sy9gSxMVp7odTqsE6yEXF9mGKzFt6iaa5J",
	"1ln2PBpc99nYVN3VXp3Wrlup9yoR6hx2DU69aXBT8ja9c+8q36IN6wWDdNjWqL1wP8A1he+75sbY3t/S",
	"5BeWpI89Bp2XpzkGrf7qYYWc0MwLVfLMTwA318bU3x5tkkJSvfxodizn8gqIBGn2vObX24rUv/z5e6Xv",
	"jSX3tCH4QmvhdlAjEC0Iqu1EPlu+4+8Jm78UAr08PzV7OUjl9tfJcXQcGehcACOC4hg/O46On2EzTvTC",
	"ogpTohZXnMg0vJ6EZrqHmdHBNmXcldkkzo6w09RoFq70m+qlPyYmIKucsasUKP2Kp8t7SLDh2gii1Hcu",
	"0908cTZab0y9aqx5RcsCNg9LP0bRkLap14XdU8M6wCfRZPdbfaFnWVNrNWsVfad6gWwo6AdUhxJgTebK",
	"RGnJNDVvdsvYketz8BTxHbRreFavDzqXFwPHhmZJWJ61zYlhx0q7cYxY53aW9fQutfAel+5RkgA/H+PW",
	"d4xtDwGbyHb7f5qa+FrVpkqjvFWEqsC1BJoa9o9px3Yp79qO28S8X3ePaqbJg4FoDpf9Q4UDmNbpdPUf",
	"UcXNq5F7tvLY2ju8iDSAveUf7vFwRdO1u7nKQEOfIW/s/30cOU37DW+vn8z20Nw+2b22W9322a+nGPu9",
	"e9K/WavP8Q52uq98u2zszHdwq7m5t0RGe+mhVm202Uf3VJp3oEfURRS+KVjsvS4PP1v9Yn68UHl0XjiA",
	"T2e2Ory3n63tS8ARY+C8Wv546sl+AHh4lRVsTmV3kEJ8hsocoANjwE7oAAnJE7AXPgHisrywG/oyVJ7J",
	"PI3UaPZN95VT25A+o/bBsME7qUbfBfKeCGqFn2joU5Gzui4ZLftaFHw81bdxAbBn0VdftA9rPtHcxT8J",
	"yVfh9RV+cCjdXu9V5HjQ3XBLz534Pim7xv63xN62TI+SFHvI4WMJiru0bbSPtq3kxBNp21pN3L1tQ2kv",
	"hu2d12045+6TnxDzvBfg45nX5clHJ0rKDzL/dZq40Bv95GAjJ4cO/aSx9uV1VdZCZuWlbxyGGU9ItuBK",
	"xy+iF5G9GSstrLZ/TwWWCk6dKCjJYRH3ZVd93ssJI3MoyV2+0/qSPzTVfa/VfT9d/xMAAP//k/xEOiAl",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
