// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateMerchantRequest defines model for CreateMerchantRequest.
type CreateMerchantRequest struct {
	Name string `json:"name"`
}

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	Amount     string `json:"amount"`
	MerchantId int    `json:"merchant_id"`
	Status     string `json:"status"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Merchant defines model for Merchant.
type Merchant struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int       `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int `json:"limit"`
	Page       int `json:"page"`
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount       *string    `json:"amount,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Id           *string    `json:"id,omitempty"`
	MerchantId   *int       `json:"merchant_id,omitempty"`
	MerchantName *string    `json:"merchant_name,omitempty"`
	Status       *string    `json:"status,omitempty"`
}

// ReviewPaymentRequest defines model for ReviewPaymentRequest.
type ReviewPaymentRequest struct {
	Status string `json:"status"`
}

// UpdateMerchantRequest defines model for UpdateMerchantRequest.
type UpdateMerchantRequest struct {
	Name string `json:"name"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	Password string `json:"password"`
}

// UpdatePaymentRequest defines model for UpdatePaymentRequest.
type UpdatePaymentRequest struct {
	Amount     string `json:"amount"`
	MerchantId int    `json:"merchant_id"`
	Status     string `json:"status"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Email string `json:"email"`
	Role  string `json:"role"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// UserRecord defines model for UserRecord.
type UserRecord struct {
	Email *string `json:"email,omitempty"`
	Id    *string `json:"id,omitempty"`
	Role  *string `json:"role,omitempty"`
}

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// Search defines model for search.
type Search = string

// Sort defines model for sort.
type Sort = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// MerchantListResponse defines model for MerchantListResponse.
type MerchantListResponse struct {
	Limit      int        `json:"limit"`
	Merchants  []Merchant `json:"merchants"`
	Page       int        `json:"page"`
	Total      int        `json:"total"`
	TotalPages int        `json:"total_pages"`
}

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments *[]Payment `json:"payments,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Limit      int          `json:"limit"`
	Page       int          `json:"page"`
	Total      int          `json:"total"`
	TotalPages int          `json:"total_pages"`
	Users      []UserRecord `json:"users"`
}

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1MerchantsParams defines parameters for GetDashboardV1Merchants.
type GetDashboardV1MerchantsParams struct {
	// Search Free-text search term for list filtering
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Page Page number (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Search Free-text search term for list filtering
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Page Page number (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Status status of payment (completed, processing, or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// GetDashboardV1UsersParams defines parameters for GetDashboardV1Users.
type GetDashboardV1UsersParams struct {
	// Search Free-text search term for list filtering
	Search *Search `form:"search,omitempty" json:"search,omitempty"`

	// Page Page number (1-based)
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page (max 100)
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// PostDashboardV1MerchantsJSONRequestBody defines body for PostDashboardV1Merchants for application/json ContentType.
type PostDashboardV1MerchantsJSONRequestBody = CreateMerchantRequest

// PutDashboardV1MerchantsIdJSONRequestBody defines body for PutDashboardV1MerchantsId for application/json ContentType.
type PutDashboardV1MerchantsIdJSONRequestBody = UpdateMerchantRequest

// PostDashboardV1PaymentsJSONRequestBody defines body for PostDashboardV1Payments for application/json ContentType.
type PostDashboardV1PaymentsJSONRequestBody = CreatePaymentRequest

// PutDashboardV1PaymentsIdJSONRequestBody defines body for PutDashboardV1PaymentsId for application/json ContentType.
type PutDashboardV1PaymentsIdJSONRequestBody = UpdatePaymentRequest

// PutDashboardV1PaymentsIdReviewJSONRequestBody defines body for PutDashboardV1PaymentsIdReview for application/json ContentType.
type PutDashboardV1PaymentsIdReviewJSONRequestBody = ReviewPaymentRequest

// PostDashboardV1UsersJSONRequestBody defines body for PostDashboardV1Users for application/json ContentType.
type PostDashboardV1UsersJSONRequestBody = CreateUserRequest

// PutDashboardV1UsersIdJSONRequestBody defines body for PutDashboardV1UsersId for application/json ContentType.
type PutDashboardV1UsersIdJSONRequestBody = UpdateUserRequest

// PatchDashboardV1UsersIdPasswordJSONRequestBody defines body for PatchDashboardV1UsersIdPassword for application/json ContentType.
type PatchDashboardV1UsersIdPasswordJSONRequestBody = UpdatePasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List merchants
	// (GET /dashboard/v1/merchants)
	GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request, params GetDashboardV1MerchantsParams)
	// Create a merchant
	// (POST /dashboard/v1/merchants)
	PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request)
	// Delete a merchant
	// (DELETE /dashboard/v1/merchants/{id})
	DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// Get a merchant
	// (GET /dashboard/v1/merchants/{id})
	GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// Update a merchant
	// (PUT /dashboard/v1/merchants/{id})
	PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int)
	// List payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
	// Create a payment
	// (POST /dashboard/v1/payments)
	PostDashboardV1Payments(w http.ResponseWriter, r *http.Request)
	// Delete a payment
	// (DELETE /dashboard/v1/payments/{id})
	DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string)
	// Update a payment
	// (PUT /dashboard/v1/payments/{id})
	PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string)
	// Review payment (update status)
	// (PUT /dashboard/v1/payments/{id}/review)
	PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request, id string)
	// List users
	// (GET /dashboard/v1/users)
	GetDashboardV1Users(w http.ResponseWriter, r *http.Request, params GetDashboardV1UsersParams)
	// Create a user
	// (POST /dashboard/v1/users)
	PostDashboardV1Users(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /dashboard/v1/users/{id})
	DeleteDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int)
	// Get a user
	// (GET /dashboard/v1/users/{id})
	GetDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int)
	// Update a user
	// (PUT /dashboard/v1/users/{id})
	PutDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int)
	// Update user password
	// (PATCH /dashboard/v1/users/{id}/password)
	PatchDashboardV1UsersIdPassword(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List merchants
// (GET /dashboard/v1/merchants)
func (_ Unimplemented) GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request, params GetDashboardV1MerchantsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a merchant
// (POST /dashboard/v1/merchants)
func (_ Unimplemented) PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a merchant
// (DELETE /dashboard/v1/merchants/{id})
func (_ Unimplemented) DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a merchant
// (GET /dashboard/v1/merchants/{id})
func (_ Unimplemented) GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a merchant
// (PUT /dashboard/v1/merchants/{id})
func (_ Unimplemented) PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a payment
// (POST /dashboard/v1/payments)
func (_ Unimplemented) PostDashboardV1Payments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a payment
// (DELETE /dashboard/v1/payments/{id})
func (_ Unimplemented) DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a payment
// (PUT /dashboard/v1/payments/{id})
func (_ Unimplemented) PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Review payment (update status)
// (PUT /dashboard/v1/payments/{id}/review)
func (_ Unimplemented) PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /dashboard/v1/users)
func (_ Unimplemented) GetDashboardV1Users(w http.ResponseWriter, r *http.Request, params GetDashboardV1UsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /dashboard/v1/users)
func (_ Unimplemented) PostDashboardV1Users(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user
// (DELETE /dashboard/v1/users/{id})
func (_ Unimplemented) DeleteDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a user
// (GET /dashboard/v1/users/{id})
func (_ Unimplemented) GetDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user
// (PUT /dashboard/v1/users/{id})
func (_ Unimplemented) PutDashboardV1UsersId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user password
// (PATCH /dashboard/v1/users/{id}/password)
func (_ Unimplemented) PatchDashboardV1UsersIdPassword(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Merchants operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1MerchantsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Merchants(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1Merchants operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1Merchants(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1Merchants(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1MerchantsId operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1MerchantsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1MerchantsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1Payments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDashboardV1PaymentsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDashboardV1PaymentsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentsId operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1PaymentsIdReview operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1PaymentsIdReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1PaymentsIdReview(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Users operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Users(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1UsersParams

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Users(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1Users operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1Users(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1Users(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDashboardV1UsersId operation middleware
func (siw *ServerInterfaceWrapper) DeleteDashboardV1UsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDashboardV1UsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1UsersId operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1UsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1UsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDashboardV1UsersId operation middleware
func (siw *ServerInterfaceWrapper) PutDashboardV1UsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDashboardV1UsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchDashboardV1UsersIdPassword operation middleware
func (siw *ServerInterfaceWrapper) PatchDashboardV1UsersIdPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchDashboardV1UsersIdPassword(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/merchants", wrapper.GetDashboardV1Merchants)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/merchants", wrapper.PostDashboardV1Merchants)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.DeleteDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.GetDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/merchants/{id}", wrapper.PutDashboardV1MerchantsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/payments", wrapper.PostDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dashboard/v1/payments/{id}", wrapper.DeleteDashboardV1PaymentsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payments/{id}", wrapper.PutDashboardV1PaymentsId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/payments/{id}/review", wrapper.PutDashboardV1PaymentsIdReview)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/users", wrapper.GetDashboardV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/users", wrapper.PostDashboardV1Users)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dashboard/v1/users/{id}", wrapper.DeleteDashboardV1UsersId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/users/{id}", wrapper.GetDashboardV1UsersId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dashboard/v1/users/{id}", wrapper.PutDashboardV1UsersId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/dashboard/v1/users/{id}/password", wrapper.PatchDashboardV1UsersIdPassword)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW2/bOhL+KwR3HxKsEsvbFCgE7EMv2yKLZjdIN7sPPUbDSGObrUSqJJXGx/B/P+BF",
	"F1uULTuxc/wWR9TMN1d+HGqOY57lnAFTEkdznBNBMlAgzK+UZlTpPxKQsaC5opzhCP+7yO5BID5GVEEm",
	"UQ4C5WQC6CQjj2gYhqc4wFSv/FmAmOEAM5IBjpy8AMt4ChmxgsekSBWOhmGAM/JIsyLTP/QvytyvAKtZ",
	"rt+nTMEEBF4sAqwVtqFdaxjM4jsZnt0TCUkXGiPBD2ajdglExNO2/o8C4EzBo0J2BVIgMjTmAqVUKjSm",
	"qQJB2aQDkhPbBAWPJMtT/VDxHxxXaKQycgwYLjxRes+zjJxJ0CFVkCC9Co0ppIk8R/ohZygnSoFgMkJ3",
	"Z7EAve4bUXfoJBcwpo/o7uwO/QNpuafojmS8YPoh42jpOZHx6W+syyQNzm9QQ6XHrkWABcicMwkmGd+R",
	"5AZ+FiDVP4XgQv8r5kwBM7aTPE9pTLTtg+9SO2De0PlXAWMc4b8M6mwf2KdyYKUZfcsOdNrQA0lpYiSj",
	"MaEpJHgR4EumHUfSLyAeQBwIUakUSaMVgV0Y4M98QtmN89az4biV4IUhQBWCIcV/AEOEJaiQIBBlYy4y",
	"o0dDugIRTwlTn6lUOyEjafqfMY6+rsd4TSaUGRFXoAheBHOcC56DUNSmTeZwmB+mX20yu0SurXBJSYQg",
	"M2xT8mdBBSQ4+toQPapW8vvvECu8GHn8VgpG2ida+jWZZfAEFy1bmltp/Q116r12rpjTNsa9XNlyy0ih",
	"plzQ3yHpWw6uFRighXkfmNKLtH/nWBZZRsRMe45KSdkEcZ1mph5t9uEAP5C0cF5LAEcXoW7eIKXZHnDm",
	"XtSy0RRIUmb0EyvxbY217gsaXqkwFpDoBSSVxjsSxEtXgq7S/smhEd9AzEWysQ6s4H41oMW6nKmiYLC8",
	"N3tBWSKu97aT3O4qc88u2ERkVrUBBU6Ly91OJXan86gJqpr/RpPG84oaBFgqogq5GWJTUFBqrF7vxm7j",
	"0gEcMkJTL+6cSPlLB9P3UPC0h1Ot8IYo96IPa9UBlvHZGm1wAFOubSdWBdykC7fLHSKqas3TFdZbYmDU",
	"WnwGVJtA24aatERzbPc8HOGEKDhTNIO29gB3JUtHNge4yJMtlSw8Rqy0hJYpFb+vnKxpeBtmvhoLb9AU",
	"VyRdWvY67Fz3TcuUy6u9TLsZN8fYy2OEVbgscOR1g93ntqnzJ0d5i5ZRLehMh3VNpWXuDTxQ+LWpx/Xt",
	"U2sa0q1J0n23bKvl2jWdTi1rGlwri9zKddqOcYOw2HfcILbbAzobvzkzPF2tLmrdyftlfIOrbKGabrsZ",
	"rnLiAEuIC0HV7IvmMVbfPRABQvPD+tfHsn386///Lc/CWpJ9WreSqVK5ZZv6MGVAUGX2vqvZJ/6ZsMnb",
	"PEdvry817wUhLaUanofnoUbOc2AkpzjCr87D81dmq1ZTg2qQEDm950Qkg4fhQO+jg1SfGY2/uM0U7TWz",
	"WVwmmt9zqT6UL/1vqA0yp0xsEwKkeseT2ROOKztxlU2UZOQ9udSvKFHA6mDh72HYRYardYPlE/YiwBfh",
	"cPNb7UORyZrqXGOkol9UTZExBf0NNdiVIhOprTTJNNJvLodx6Wg7AU8QP0EzhlfV+mBp0NdxsKiXDNxc",
	"Sp8pNqw0W3SPdXYPX4x2iYV3tPCEkAT4dR+1vpFPswkYRzbL/+tI29eINpUKZY0glAGuyOZIZ3+fcmyG",
	"ctdyXHf685/GehXT8NlA1IOY9jnSAkwqd9r494ji6hjxiaXcN/YWLyI1YG/4u2t8MKfJwk55U1DQzpAP",
	"5v++HLlM2gVvRrV6e6gntYZnLEe3OSdpcfN27V60p9DVzMvCTg7lb+uNjf4OtuqbB3NkeJAaasRG6X30",
	"QKH5BKpHXPLC1wWLg8fl+Xur/9jUn6jsPS8swOPprRbv9r21OTDv0Qauy+X7Y0/msuz5WVaw2pXtIRLx",
	"MXI+QCdagOnQAcoFj8GM1gLEhRtud92iuvOop5Bqzr6qvlRqCtIn1DzoFrgTa/RdthwoQQ3xy+v0KZOz",
	"HEz1pn2NFNwf61sZfhyY9FWXUt2cL6/vrY6C8pV4fYHvbErb870yOZ51N1xTcxe+zy9sYb8U2Vvn6V6U",
	"4gA+3Beh2KVsw0OUbUknjqRsKzaxe9kOhBnBm5nXNjlnJ/dHlHneq4b+mbecJ18sKXFXX3/2NLGm1/zJ",
	"wkaWDp32S5rqRr4H+7w1a497cNf6CuKQ/KtwDizjYm4qejOv0v37o13Ne5sDc67mtx7dtKuQII6Gcxmw",
	"rWD7K3B7qmWy4SXHauYzmpdiWX7fBr272BGO0dZXiIvG4YdoXZHowTr2Hol98dyt++TBssDx3GPokxXJ",
	"3bpPDpq3szlR9iv4lUzT/27n2nV9tXlkObf69cmuFLeUcywk16WJ+b7bczFdZosRKR7KaBYidR8zRINB",
	"ymOSTrlU0ZvwTWiIo3t9vv6bWmBJzqkddrmcMCDb48TqHiMjjEzAHdrcO42vubumFb7XqvPsaPFHAAAA",
	"//8gLb2cJDMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
